# Generated by Django 3.2 on 2021-04-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0004_auto_20210419_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zbozi',
            name='stav',
            field=models.IntegerField(blank=True, choices=[(1, '>200000'), (2, '<150000'), (3, '<100000'), (4, '<50000'), (5, 'Nové')], default=3, help_text='Vyberte označení stavu', max_length=1, verbose_name='Stav zboží'),
        ),
    ]
