# Generated by Django 3.2 on 2021-05-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0007_auto_20210504_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zbozi',
            name='rok',
            field=models.IntegerField(help_text='Zadejte nezáporné číslo', null=True, verbose_name='Rok'),
        ),
    ]
